version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing dependencies...
      - pip install Flask
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t my-flask-app .
      - echo Tagging the Docker image...
      - docker tag my-flask-app:latest 730335380235.dkr.ecr.us-east-1.amazonaws.com/akashecr:latest
  post_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 730335380235.dkr.ecr.us-east-1.amazonaws.com
      - echo Pushing the Docker image to ECR...
      - docker push 730335380235.dkr.ecr.us-east-1.amazonaws.com/akashecr:latest
